// Code generated by protoc-gen-go.
// source: index.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	index.proto
	metadata.proto

It has these top-level messages:
	Entry
	Meta
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Entry struct {
	LastUsed         *int64 `protobuf:"varint,1,opt,name=lastUsed" json:"lastUsed,omitempty"`
	Size             *int64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	UseCount         *int32 `protobuf:"varint,3,opt,name=useCount" json:"useCount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Entry) Reset()                    { *m = Entry{} }
func (m *Entry) String() string            { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()               {}
func (*Entry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Entry) GetLastUsed() int64 {
	if m != nil && m.LastUsed != nil {
		return *m.LastUsed
	}
	return 0
}

func (m *Entry) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *Entry) GetUseCount() int32 {
	if m != nil && m.UseCount != nil {
		return *m.UseCount
	}
	return 0
}

func init() {
	proto.RegisterType((*Entry)(nil), "pb.Entry")
}

var fileDescriptor0 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcc, 0x4b, 0x49,
	0xad, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0xb2, 0xe4, 0x62, 0x75,
	0xcd, 0x2b, 0x29, 0xaa, 0x14, 0x12, 0xe0, 0xe2, 0xc8, 0x49, 0x2c, 0x2e, 0x09, 0x2d, 0x4e, 0x4d,
	0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x16, 0xe2, 0xe1, 0x62, 0x29, 0xce, 0xac, 0x4a, 0x95, 0x60,
	0x02, 0xf3, 0x80, 0xf2, 0xa5, 0xc5, 0xa9, 0xce, 0xf9, 0xa5, 0x79, 0x25, 0x12, 0xcc, 0x40, 0x11,
	0x56, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0xce, 0x91, 0xcd, 0x4c, 0x00, 0x00, 0x00,
}
