// Code generated by protoc-gen-go.
// source: index.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	index.proto
	metadata.proto

It has these top-level messages:
	Entry
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Entry struct {
	LastUsed         *int64 `protobuf:"varint,1,opt,name=lastUsed" json:"lastUsed,omitempty"`
	Size             *int64 `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	UseCount         *int32 `protobuf:"varint,3,opt,name=useCount" json:"useCount,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Entry) Reset()         { *m = Entry{} }
func (m *Entry) String() string { return proto.CompactTextString(m) }
func (*Entry) ProtoMessage()    {}

func (m *Entry) GetLastUsed() int64 {
	if m != nil && m.LastUsed != nil {
		return *m.LastUsed
	}
	return 0
}

func (m *Entry) GetSize() int64 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *Entry) GetUseCount() int32 {
	if m != nil && m.UseCount != nil {
		return *m.UseCount
	}
	return 0
}
