// Code generated by protoc-gen-go.
// source: metadata.proto
// DO NOT EDIT!

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Meta struct {
	StatusCode       *int32   `protobuf:"varint,1,opt" json:"StatusCode,omitempty"`
	Header           []string `protobuf:"bytes,2,rep" json:"Header,omitempty"`
	ResponseTime     *int64   `protobuf:"varint,3,opt" json:"ResponseTime,omitempty"`
	ResponseDelay    *int64   `protobuf:"varint,4,opt" json:"ResponseDelay,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Meta) Reset()         { *m = Meta{} }
func (m *Meta) String() string { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()    {}

func (m *Meta) GetStatusCode() int32 {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return 0
}

func (m *Meta) GetHeader() []string {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Meta) GetResponseTime() int64 {
	if m != nil && m.ResponseTime != nil {
		return *m.ResponseTime
	}
	return 0
}

func (m *Meta) GetResponseDelay() int64 {
	if m != nil && m.ResponseDelay != nil {
		return *m.ResponseDelay
	}
	return 0
}
